baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "What I talk about when I don't talk about me"
theme = "blackburn"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Technical Posts"
    weight = 2
    identifier = "technical-posts"
    url = "/technical-posts/"
[[menu.main]]
    name = "Other Musings"
    weight = 3
    identifier = "other-musings"
    url = "/other-musings/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Runze"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/runze-wang-413a091a/"

[params]
    description = "A website built through Hugo and blogdown."
    
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    
    # disqus = "runze-ds-blog"
    
    dateFormat = "2006-01-02"
    