baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "What I talk about when I don't talk about me"
theme = "blackburn"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Runze"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/runze-wang-413a091a/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/runze_w"

[params]
    description = "A website built through Hugo and blogdown."
    
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    
    disqus = "runze-ds-blog"
    
    dateFormat = "2006-01-02"
    